#server
server:
  port: 80
  servlet:
    context-path: /
  tomcat:
    max-threads: 1000
    min-spare-threads: 100
    uri-encoding: UTF-8

#spring
spring:
  datasource:
    url: jdbc:mysql:///survivor?characterEncoding=utf-8&serverTimezone=GMT
    username: root
    password: 123456
  thymeleaf:
    prefix: classpath:/templates/pages/
    suffix: .html

#mybatis
mybatis:
  configuration:
    default-statement-timeout: 30
    map-underscore-to-camel-case: true
  mapper-locations:
  - classpath:/mapper/sys/*.xml

